#!/usr/bin/env python

import sys

from CliCmdSas    import CliCmdSas
from CliCmdSerial import CliCmdSerial

device = sys.argv[1]
if "sg"  in device: cli = CliCmdSas   (device, int(sys.argv[2]))
if "tty" in device: cli = CliCmdSerial(device)

while True:
    print "command:",
    try:
        rawinp = raw_input()
    except KeyboardInterrupt:
        print
        sys.exit()
    except EOFError:
        print
        sys.exit()

    print cli.execute(rawinp)
