#!/usr/bin/env python

from CliCmdSerial import CliCmdSerial

cli = CliCmdSerial("/dev/ttyUSB0")

page0 = cli.execute("ses rcv 0")
print 'vvvvvvvvvv page 0'
print page0
print '^^^^^^^^^^ page 0'

page2 = cli.execute("ses rcv 2")
print 'vvvvvvvvvv page 2'
print page2
print '^^^^^^^^^^ page 2'

