#!/usr/bin/env python

import sys

from CliCmdSas    import CliCmdSas
from CliCmdSerial import CliCmdSerial

progname = sys.argv.pop(0)
#id       = sys.argv.pop(0)

#cli = CliCmdSas("/dev/sg4", int(id))
cli = CliCmdSerial("/dev/ttyUSB0")
print cli.execute(" ".join(sys.argv))
