#!/usr/bin/env python

from Menu import *

def first():
    print "first operation"
    
def second():
    print "second operation"
    
def third():
    print "third operation"
    
def subone():
    print "sub menu item 1"

    
submenu = Menu("Sub Menu 1",
            [
            ['Exit'   , Menu.stop],
            ['Sub one', subone],
            ])

menu = Menu("Main Menu",
        [
        ['Exit'            , Menu.stop],
        ['Operation first' , first ],
        ['Operation second', second],
        ['Operation third' , third ],
        ['Invoke sub menu' , submenu.run],
        ])

menu.run()
