#!/usr/bin/env python

import sys

from CliCmdSas    import CliCmdSas
from CliCmdSerial import CliCmdSerial

device = sys.argv[1]
if "sg"  in device: cli = CliCmdSas   (device, 3)
if "tty" in device: cli = CliCmdSerial(device)

print cli.execute("adpcol dis")
print cli.execute("fan speed 1 0xfff")
