#!/usr/bin/env python

import sys

from discovery import Discovery

Discovery.probe()
cli = Discovery.create_best((Discovery.CAP_FAN_CONTROL,))

print cli.execute("adpcol dis")
print cli.execute("fan speed 1 0xfff")
