#!/usr/bin/env python

from discovery import Discovery

print Discovery.discover_sas()
print Discovery.discover_serial()

print
Discovery.probe()
#print Discovery.capabilities
for cap,val in Discovery.capabilities.items():
    print "capability:", Discovery.description[cap]
    for ad in sorted(val, key=lambda a: a[0]):
        print "   ", ad[0], ad[2]
