#!/usr/bin/env python

import sys
import os

from firmwarefile import FirmwareFile

#print FirmwareFile("").identifyfile(sys.argv[1])
#print FirmwareFile(sys.argv[1]).get_all()

# print "type subtype   d vers destination filename"
# for f in FirmwareFile(sys.argv[1]).get_list():
#     print "%-14s %d %-4s %-11s %s" % (f[2][2], f[2][1], f[1], ','.join(f[2][0]), f[0].split('/')[-1])

filenames = FirmwareFile(sys.argv[1], verbosity=1).get_filename()
for expander in filenames:
    print "expander:", expander
    for typ in filenames[expander]:
        print "  typ:", typ
        for version in filenames[expander][typ]:
            filename = filenames[expander][typ][version]
            print "    version:", version, " filename:", filename.split('/')[-1]
