#!/usr/bin/env python

import sys
import os

from firmwarefile import FirmwareFile

#print FirmwareFile("").identifyfile(sys.argv[1])
#print FirmwareFile(sys.argv[1]).get_all()

# print "type subtype   d vers destination filename"
# for f in FirmwareFile(sys.argv[1]).get_list():
#     print "%-14s %d %-4s %-11s %s" % (f[2][2], f[2][1], f[1], ','.join(f[2][0]), f[0].split('/')[-1])

filenames = FirmwareFile(sys.argv[1], verbosity=1).get_filename()
for expander in sorted(filenames):
    print "expander:", expander
    for typ in sorted(filenames[expander]):
        print "  typ:", typ
        for version in sorted(filenames[expander][typ]):
            filename = filenames[expander][typ][version]
            print "    version: %-6s" % version, " filename:", filename.split('/')[-1]

# ff = FirmwareFile(sys.argv[1])
# prog = ff.parse_plx(sys.argv[1])
# for entry in prog:
#     print "%3X:%2X %8X" % entry

# ff = FirmwareFile(sys.argv[1], verbosity=3)
# jbl = ff.parse_jbl(sys.argv[1])
# for j in jbl:
#     print "%.2x %.2x %.2x  %s" % (ord(j[0][0]), ord(j[0][1]), ord(j[0][2]), j[1])
